### GET 
GET http://localhost:5050/ HTTP/1.1

### GET all intakes
GET http://localhost:5050/intakes HTTP/1.1

###Get One intakes
GET http://localhost:5050/intakes/747698df-43c7-4a8d-9ade-7f96bf5ec530 HTTP/1.1

### Post intakes
POST http://localhost:5050/intakes HTTP/1.1
Content-Type: application/json

{
    "datetime" : "2020-06-26T22:00:34.696Z",
    "TreatmentId": "03ae8093-7e13-4fff-924d-fe5b07e0d4dc",
    "DrugId": "264e6072-1ad6-4dee-9abd-cfdb0afec8c3",
    "dosage": 1000
}

### Put Intakes
PUT http://localhost:5050/intakes/df54c122-ca32-46bb-b711-963a7971f5f0 HTTP/1.1
Content-Type: application/json

{ 
    "datetime" : 789000,
    "used" : false 
}

### DELETE Intakes
DELETE http://localhost:5050/intakes/df54c122-ca32-46bb-b711-963a7971f5f0 HTTP/1.1
