### GET 
GET http://localhost:5050/ HTTP/1.1

### GET all Treatments
GET http://localhost:5050/treatments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTBkMzVhLTU2MmEtNDhiOC05ZTJiLTU5NGU5ZmZjMmE4MiIsImVtYWlsIjoiamVhbmR1cG9udEBnbWFpbC5jb20iLCJpYXQiOjE1OTMxNTcwOTksImV4cCI6MTU5MzI0MzQ5OX0.V0xpiSHV3rLS6z-LI35xBZ5A57Drf4VRZPR2Mbpk6r8

###Get One Treamtments
GET http://localhost:5050/treatments/05a535f8-3ae7-4600-8c4b-a38987766ce4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTBkMzVhLTU2MmEtNDhiOC05ZTJiLTU5NGU5ZmZjMmE4MiIsImVtYWlsIjoiamVhbmR1cG9udEBnbWFpbC5jb20iLCJpYXQiOjE1OTMxNTcwOTksImV4cCI6MTU5MzI0MzQ5OX0.V0xpiSHV3rLS6z-LI35xBZ5A57Drf4VRZPR2Mbpk6r8


### Post Treatment
POST http://localhost:5050/treatments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTBkMzVhLTU2MmEtNDhiOC05ZTJiLTU5NGU5ZmZjMmE4MiIsImVtYWlsIjoiamVhbmR1cG9udEBnbWFpbC5jb20iLCJpYXQiOjE1OTMxNTcwOTksImV4cCI6MTU5MzI0MzQ5OX0.V0xpiSHV3rLS6z-LI35xBZ5A57Drf4VRZPR2Mbpk6r8
Content-Type: application/json

{
    "startDate":"2020-06-26",
    "endDate":"2020-07-03"
}

### Put Treatment
PUT http://localhost:5050/treatments/b0d9fdda-5bb2-4f2a-9dca-963161934a28 HTTP/1.1
Content-Type: application/json

{ 
    "name" : "Grippe",
    "duration" : 7 
}

### DELETE Treatment
DELETE http://localhost:5050/treatments/b0d9fdda-5bb2-4f2a-9dca-963161934a28 HTTP/1.1


